In [1]:
import keras

keras.__version__

Using TensorFlow backend.


'2.2.4'

In [2]:
import numpy as np

In [3]:
# 0D 텐서 / 스칼라
x = np.array(12)
print(x)
print(x.ndim)
print(x.shape)

12
0
()


In [4]:
# 1D 텐서 / 벡터

x = np.array([12,3,6,14,7])
print(x)
print(x.ndim)
print(x.shape)

[12  3  6 14  7]
1
(5,)


In [5]:
# 2D 텐서 / 행렬

x = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(x)
print(x.ndim)
print(x.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
2
(3, 5)


- shape는 각 축을 따라 얼마나 많은 차원이 있는지를 나타내는 파이썬의 튜플이다.
- 벡터(1D텐서)는 1개의 원소로 이루어진 튜플 / 스칼라는 크기가 없다.
- 데이터 타입 또한 텐서에 포함된다.

In [6]:
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [7]:
# 넘파이로 텐서 조작하기

slice_AM = train_images[10:100]
print(slice_AM.shape)

slice_FM = train_images[10:100, : , : ]
print(slice_FM.shape)

(90, 28, 28)
(90, 28, 28)


<b>데이터 표시</b>
- 벡터 데이터 : 2D텐서 / (샘플축(행), 특성축(렬))
- 시계열 또는 시퀀스 데이터 : 3D텐서 / (샘플 수, 타임 스텝(행), 특성축(렬))
- 이미지 데이터 : 4D텐서 / (샘플 수, 높이(행), 너비(렬), 채널 수)

<br>

## 텐서 연산 Tensor Operation

<b>브로드캐스팅: 큰 텐서의 크기에 맞춰, 작은 텐서를 연산할 수 있다.</b>
- 큰 텐서의 ndim에 맞도록 작은 텐서에 축이 추가된다.
- 작은 텐서가 새 축을 따라서 큰 텐서의 크기에 맞도록 반복된다.


In [8]:
def braodcast(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] += y[j]
    return x


In [ ]:
# 텐서 점곱

import numpy as np

z = np.dot(x, y)
z = x @ y

def naive_vector_dot(x,y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    
    z = 0.
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z