In [1]:
import numpy as np
import pandas as pd

samsung = np.load("samsung.npy")
kospi200 = np.load("kospi200.npy")

print(samsung)
print(kospi200)

##########################################################################################
               
def split_xy(dataset, n_steps, y_column):
    x,y = list(), list()
    for i in range(len(dataset)):     
        x_end_number = i + n_steps
        y_end_number = x_end_number + y_column
        if y_end_number > len(dataset):  
            break
            
        tmp_x, tmp_y = dataset[i:x_end_number, : ], dataset[x_end_number:y_end_number, 3] 
        x.append(tmp_x)                                      
        y.append(tmp_y)
    return np.array(x), np.array(y)

x1, y1 = split_xy(samsung,5,1)
x2, y2 = split_xy(kospi200,5,1)
print(x1[0,:], '\n',y1[0])
print(x2[0,:], '\n',y2[0])

[[   53000    53900    51800    51900 39565391]
 [   52600    53200    51900    52600 23104720]
 [   52600    52800    50900    50900 16128305]
 ...
 [   59100    59700    58800    59100 16446102]
 [   58800    58800    56800    57200 20821939]
 [   57800    58400    56400    56400 19749457]]
[[   320.56    321.      316.75    316.75 173911.  ]
 [   317.79    319.53    314.95    315.87 141252.  ]
 [   315.93    316.08    312.6     314.42 123610.  ]
 ...
 [   294.38    295.67    292.45    293.98  85731.  ]
 [   293.27    294.11    287.09    288.37 101535.  ]
 [   290.24    291.47    284.53    284.53 101455.  ]]
[[   53000    53900    51800    51900 39565391]
 [   52600    53200    51900    52600 23104720]
 [   52600    52800    50900    50900 16128305]
 [   51700    51700    50600    51600 13905263]
 [   52000    52200    51200    51300 10314997]] 
 [50100]
[[   320.56    321.      316.75    316.75 173911.  ]
 [   317.79    319.53    314.95    315.87 141252.  ]
 [   315.93    316.08    

In [2]:
print(x1.shape, y1.shape, x2.shape, y2.shape)

(421, 5, 5) (421, 1) (421, 5, 5) (421, 1)


In [3]:
# 데이터셋 나누기
from sklearn.model_selection import train_test_split

x1_train, x1_test, y1_train, y1_test = train_test_split(x1,y1, 
                                                   random_state=1,
                                                    test_size=0.6,
                                                    shuffle=False)
x2_train, x2_test, y2_train, y2_test = train_test_split(x2,y2, 
                                                   random_state=1,
                                                    test_size=0.6,
                                                    shuffle=False)

In [4]:
# 데이터 전처리 StandardScaler
from sklearn.preprocessing import StandardScaler

x1_train = np.reshape(x1_train, (x1_train.shape[0], x1_train.shape[1] * x1_train.shape[2]))
x1_test = np.reshape(x1_test, (x1_test.shape[0], x1_test.shape[1] * x1_test.shape[2]))
                          
scaler = StandardScaler()
scaler.fit(x1_train)

x1_train = scaler.transform(x1_train) 
x1_test = scaler.transform(x1_test)

##########################################################################################

x2_train = np.reshape(x2_train, (x2_train.shape[0], x2_train.shape[1] * x2_train.shape[2]))
x2_test = np.reshape(x2_test, (x2_test.shape[0], x2_test.shape[1] * x2_test.shape[2]))
                          
#scaler = StandardScaler()
#scaler.fit(x2_train)

x2_train = scaler.transform(x2_train) 
x2_test = scaler.transform(x2_test)

In [5]:
print(x1_train.shape, y1_train.shape, x2_train.shape, y2_train.shape)

(168, 25) (168, 1) (168, 25) (168, 1)


In [6]:
# 데이터 다시 Reshape (DNN 들어갈 모델 / LSTM 들어갈 모델)
x1_train = np.reshape(x1_train, (x1_train.shape[0], 5, 5))
x1_test = np.reshape(x1_test, (x1_test.shape[0], 5, 5))

##########################################################################################

x2_train = np.reshape(x2_train, (x2_train.shape[0], 5, 5))
x2_test = np.reshape(x2_test, (x2_test.shape[0], 5, 5))

In [7]:
#2. 모델 구성
from keras.models import Model
from keras import layers

input_1 = layers.Input(shape=(5,5))
input_tensor_1 = layers.LSTM(32, activation='tanh')(input_1)   # x1에 투입할 모델
hidden_layer_1 = layers.Dense(16, activation='relu')(input_tensor_1)
hidden_layer_1 = layers.Dense(8, activation='relu')(hidden_layer_1)
output_tensor_1 = layers.Dense(1, activation='relu')(hidden_layer_1)

input_2 = layers.Input(shape=(5,5))
input_tensor_2 = layers.LSTM(32, activation='tanh')(input_2)    # x2에 투입할 모델
hidden_layer_2 = layers.Dense(16, activation='relu')(input_tensor_2)
hidden_layer_2 = layers.Dense(8, activation='relu')(hidden_layer_2)
output_tensor_2 = layers.Dense(1, activation='relu')(hidden_layer_2)

from keras.layers.merge import concatenate , Add

merged_model = concatenate(inputs=[output_tensor_1, output_tensor_2])  # 두 개 이상은 []로 묶기
# merged_model = Add()([output_tensor_1, output_tensor_2])  # concatenate 대신 Add를 사용해도 가능하다.

output_tensor_3 = layers.Dense(8)(merged_model)        # 첫 번째 아웃풋 모델
output_tensor_3 = layers.Dense(1)(output_tensor_3)


model = Model(inputs=[input_1, input_2],
              outputs=output_tensor_3)

model.summary()

Using TensorFlow backend.
C:\Users\student\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\student\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\student\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\student\Anaconda3\lib\site-packages\tensorflow\python\framework\d

Instructions for updating:
Colocations handled automatically by placer.
Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 5, 5)         0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 5, 5)         0                                            
__________________________________________________________________________________________________
lstm_1 (LSTM)                   (None, 32)           4864        input_1[0][0]                    
__________________________________________________________________________________________________
lstm_2 (LSTM)                   (None, 32)           4864        input_2[0][0]                    
____________________

In [8]:
#3. 훈련
model.compile(loss='mse', optimizer='adam', metrics=['mae'])
model.fit([x1_train, x2_train], y1_train, epochs=100, batch_size=5)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
168/168 [==============================] - 1s 8ms/step - loss: 2021722944.7619 - mae: 44837.7344
Epoch 2/100
168/168 [==============================] - 0s 963us/step - loss: 2021708684.1905 - mae: 44837.5703
Epoch 3/100
168/168 [==============================] - 0s 1ms/step - loss: 2021691332.5714 - mae: 44837.3828
Epoch 4/100
168/168 [==============================] - 0s 930us/step - loss: 2021670220.9524 - mae: 44837.1406
Epoch 5/100
168/168 [==============================] - 0s 929us/step - loss: 2021645239.6190 - mae: 44836.8633
Epoch 6/100
168/168 [==============================] - 0s 990us/step - loss: 2021616220.9524 - mae: 44836.5430
Epoch 7/100
168/168 [==============================] - 0s 843us/step - loss: 2021583148.1905 - mae: 44836.1680
Epoch 8/100
168/168 [==============================] - 0s 816us/step - loss: 2021545857.5238 - mae: 44835.7578
Epoch 9/100
168/168 [==============================] - 0s 803us/step

Epoch 72/100
168/168 [==============================] - 0s 795us/step - loss: 2011935457.5238 - mae: 44728.4492
Epoch 73/100
168/168 [==============================] - 0s 790us/step - loss: 2011693275.4286 - mae: 44725.7539
Epoch 74/100
168/168 [==============================] - 0s 784us/step - loss: 2011449059.0476 - mae: 44723.0078
Epoch 75/100
168/168 [==============================] - 0s 784us/step - loss: 2011201637.3333 - mae: 44720.2578
Epoch 76/100
168/168 [==============================] - 0s 784us/step - loss: 2010952697.9048 - mae: 44717.4688
Epoch 77/100
168/168 [==============================] - 0s 790us/step - loss: 2010700913.5238 - mae: 44714.6562
Epoch 78/100
168/168 [==============================] - 0s 784us/step - loss: 2010447323.4286 - mae: 44711.8086
Epoch 79/100
168/168 [==============================] - 0s 778us/step - loss: 2010190704.7619 - mae: 44708.9531
Epoch 80/100
168/168 [==============================] - 0s 784us/step - loss: 2009932465.5238 - mae: 447

In [9]:
results_acc = model.evaluate([x1_test, x2_test], y1_test, batch_size=5)
print('results_acc: ', results_acc)

253/253 [==============================] - 0s 908us/step
results_acc:  [2297341512.347826, 47702.2734375]


In [10]:
# RMSE 만들기
from sklearn.metrics import mean_squared_error

y_predict = model.predict([x1_test,x2_test], batch_size=1)


def RMSE(y_test, y_predict):
    return np.sqrt(mean_squared_error(y_test, y_predict))

RMSE_mean = (RMSE(y1_test, y_predict[0]) + RMSE(y2_test, y_predict[1])) / 2
print("RMSE_mean :", RMSE_mean )

# R2 지표 만들기
from sklearn.metrics import r2_score

r2_1  = r2_score(y1_test, y_predict[0])
r2_2  = r2_score(y2_test, y_predict[1])
r2_mean  = (r2_1 + r2_2) / 2

print("R2 : ", r2_mean)

ValueError: Found input variables with inconsistent numbers of samples: [253, 1]

In [ ]:
for i in range(5):
    print("종가(test) : {}".format(y1_test[i]))
    print("종가(pred) : {}".format(y_predict[i]))

In [ ]:
# print(y_predict)